"""Add custom templates

Revision ID: 35442abb5f86
Revises: dfe82bb95dba
Create Date: 2026-07-09 14:04:41.164589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35442abb5f86'
down_revision: Union[str, None] = 'dfe82bb95dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_template_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_summaries_custom_template_id'), ['custom_template_id'], unique=False)
        batch_op.create_foreign_key('fk_summaries_custom_template_id', 'custom_templates', ['custom_template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_summaries_custom_template_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_summaries_custom_template_id'))
        batch_op.drop_column('custom_template_id')

    with op.batch_alter_table('custom_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_custom_templates_id'))

    op.drop_table('custom_templates')
    # ### end Alembic commands ###
