"""Add diarization columns

Revision ID: d87a19319d1f
Revises: 58ffc09e0f28
Create Date: 2026-07-08 15:46:13.449098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87a19319d1f'
down_revision: Union[str, None] = '58ffc09e0f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('diarization_status', sa.String(), server_default='none', nullable=False))
    op.add_column('transcripts', sa.Column('diarized_segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'diarized_segments')
    op.drop_column('transcripts', 'diarization_status')
    # ### end Alembic commands ###
