"""Make transcript_id nullable

Revision ID: dfe82bb95dba
Revises: c8aeff3d1560
Create Date: 2026-07-08 21:25:08.624421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe82bb95dba'
down_revision: Union[str, None] = 'c8aeff3d1560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.alter_column('transcript_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_chunks', schema=None) as batch_op:
        batch_op.alter_column('transcript_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
