"""Make diarized_segments non-nullable

Revision ID: 4b2ccd832fc7
Revises: 35442abb5f86
Create Date: 2026-07-09 23:23:37.461795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4b2ccd832fc7'
down_revision: Union[str, None] = '35442abb5f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing NULL values to '[]' before making it NOT NULL
    op.execute("UPDATE transcripts SET diarized_segments = '[]' WHERE diarized_segments IS NULL")

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('diarized_segments',
               existing_type=sqlite.JSON(),
               nullable=False,
               server_default='[]')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.alter_column('diarized_segments',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
